config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  get '/home', to: 'home#index'
  get '/about', to: 'about#index'
  get '/contact', to: 'contact#index'
  get '/products', to: 'products#index'
  get '/products/cubex2', to: 'products#cubex2'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController

	def index
	end
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

	def index
	end
	
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
	end
	
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	def index
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<section class="single-page-title">
    <div class="container text-center">
        <h2>About us</h2>
    </div>
</section>
<!-- .page-title -->

<section class="about-text ptb-100">
    <section class="section-title">
        <div class="container text-center">
            <h2>UNDER CONSTRUCTION</h2>
            <span class="bordered-icon"><i class="fa fa-circle-thin"></i></span>
        </div>
    </section>

    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <p></p>
            </div>
            <div class="col-md-6">
                <p></p>
            </div>
        </div>
    </div>

</section>
<!-- .about-text-->
<!--
<section class="skills ptb-100 gray-bg">
    <section class="section-title">
        <div class="container text-center">
            <h2>Our Professional Skills</h2>
            <span class="bordered-icon"><i class="fa fa-circle-thin"></i></span>
        </div>
    </section>

    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h3>Completely reconceptualize leading-edge e-commerce</h3>

                <p>Whereas 2.0 ideas. Energistically expedite frictionless infrastructures without user friendly quality
                    vectors. Distinctively communicate customer directed content for leading-edge web-readiness.
                    Professionally fabricate technically sound mindshare before emerging paradigms. Efficiently e-enable
                    vertical benefits after intermandated vortals.</p>

                <p>Enthusiastically innovate one-to-one technology through user-centric architectures. Dynamically
                    whiteboard global processes with compelling interfaces. Globally empower ubiquitous growth
                    strategies vis-a-vis cross-unit alignments. Collaboratively evisculate client-focused niches with
                    impactful alignments.</p>
            </div>
            <div class="col-md-6 x-progress">
                <div class="progress-wrapper">
                    <div class="progress-item">
                        <span class="progress-title">Solution</span>

                        <div class="progress">
                            <div class="progress-bar progress-bar-dealy" role="progressbar" aria-valuenow="50"
                                 aria-valuemin="0" aria-valuemax="100" style="width: 50%;"></div>
                        </div>
                        <span class="progress-percent">50%</span>
                    </div>
                    <!- - /.progress-item - ->

                    <div class="progress-item">
                        <span class="progress-title">Creativity</span>

                        <div class="progress">
                            <div class="progress-bar progress-bar-dealy" role="progressbar" aria-valuenow="90"
                                 aria-valuemin="0" aria-valuemax="100" style="width: 90%;"></div>
                        </div>
                        <span class="progress-percent">90%</span>
                    </div>
                    <!- - /.progress-item - ->

                    <div class="progress-item">
                        <span class="progress-title">Finance</span>

                        <div class="progress">
                            <div class="progress-bar progress-bar-dealy" role="progressbar" aria-valuenow="75"
                                 aria-valuemin="0" aria-valuemax="100" style="width: 75%;"></div>
                        </div>
                        <span class="progress-percent">75%</span>
                    </div>
                    <!- - /.progress-item - ->

                    <div class="progress-item">
                        <span class="progress-title">Brand</span>

                        <div class="progress">
                            <div class="progress-bar progress-bar-dealy" role="progressbar" aria-valuenow="33"
                                 aria-valuemin="0" aria-valuemax="100" style="width: 33%;"></div>
                        </div>
                        <span class="progress-percent">33%</span>
                    </div>
                    <!- - /.progress-item - ->

                    <div class="progress-item">
                        <span class="progress-title">Efficiency</span>

                        <div class="progress">
                            <div class="progress-bar progress-bar-dealy" role="progressbar" aria-valuenow="82"
                                 aria-valuemin="0" aria-valuemax="100" style="width: 82%;"></div>
                        </div>
                        <span class="progress-percent">82%</span>
                    </div>
                    <!- - /.progress-item - ->
                </div>
                <!- - /.progress-wrapper - ->
            </div>
        </div>
    </div>

</section>
<!- - .skills - ->

<section class="testimonial">
    <section class="section-title">
        <div class="container text-center">
            <h2>Satisfied Customer</h2>
            <span class="bordered-icon"><i class="fa fa-circle-thin"></i></span>
        </div>
    </section>
    <div class="container">
        <div id="testimonialSlider" class="carousel slide" data-ride="carousel">

            <!- - Wrapper for slides - ->
            <div class="carousel-inner" role="listbox">
                <div class="item active">
                    <blockquote>
                        <ul>
                            <li><%= image_tag(image_path("img-testimonial-1.jpg"))%></li>
                            <li class="name">Justus Kühn</li>
                        </ul>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum egetvel </br>lacus
                            pretium rhoncus a quis nisly Ut vehicula gravida dui in pulvinar donec</br> diam elit
                            consequat eget augue vitae aliquet sollicitudin.
                        </p>

                    </blockquote>
                </div>
                <div class="item">
                    <blockquote>
                        <ul>
                            <li><%= image_tag(image_path("img-testimonial-2.jpg"))%></li>
                            <li class="name">Lennox Arnold</li>
                        </ul>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum egetvel </br>lacus
                            pretium rhoncus a quis nisly Ut vehicula gravida dui in pulvinar donec</br> diam elit
                            consequat eget augue vitae aliquet sollicitudin.
                        </p>

                    </blockquote>
                </div>
                <div class="item">
                    <blockquote>
                        <ul>
                            <li><%= image_tag(image_path("img-testimonial-3.jpg"))%></li>
                            <li class="name">Paulina Berger</li>
                        </ul>

                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum egetvel </br>lacus
                            pretium rhoncus a quis nisly Ut vehicula gravida dui in pulvinar donec</br> diam elit
                            consequat eget augue vitae aliquet sollicitudin.
                        </p>
                    </blockquote>
                </div>
            </div>
            <!- - Controls - ->
            <a class="left carousel-control" href="#testimonialSlider" role="button" data-slide="prev">
                <span><i class="fa fa-angle-left"></i></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#testimonialSlider" role="button" data-slide="next">
                <span><i class="fa fa-angle-right"></i></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
        <!- - #testimonialSlider - ->
    </div>
</section>
<!- - .testimonial - ->

<section class="client-logo ptb-100">
    <section class="section-title">
        <div class="container text-center">
            <h2>Our Clients</h2>
            <span class="bordered-icon"><i class="fa fa-circle-thin"></i></span>
        </div>
    </section>
    <div class="container">
        <div class="row">
            <div class="col-md-2 col-sm-4 col-xs-6 section-margin">
                <a href="#"><%= image_tag(image_path("logo-client-1.jpg"))%></a>
            </div>
            <div class="col-md-2 col-sm-4 col-xs-6 section-margin">
                <a href="#"><%= image_tag(image_path("logo-client-2.jpg"))%></a>
            </div>
            <div class="col-md-2 col-sm-4 col-xs-6 section-margin">
                <a href="#"><%= image_tag(image_path("logo-client-3.jpg"))%></a>
            </div>
            <div class="col-md-2 col-sm-4 col-xs-6 section-margin">
                <a href="#"><%= image_tag(image_path("logo-client-4.jpg"))%></a>
            </div>
            <div class="col-md-2 col-sm-4 col-xs-6 section-margin">
                <a href="#"><%= image_tag(image_path("logo-client-5.jpg"))%></a>
            </div>
            <div class="col-md-2 col-sm-4 col-xs-6 section-margin">
                <a href="#"><%= image_tag(image_path("logo-client-6.jpg"))%></a>
            </div>
        </div>
    </div>
    <!- -end of .container - ->
</section>
<!- - /.client-logo - ->
-->

app/views/contact/index.html.erb
<section class="single-page-title">
    <div class="container text-center">
        <h2>Contact us</h2>
    </div>
</section>
<!-- .page-title -->

<section class="contact-form ptb-100">
    <div class="container text-center">
        <h2> If you would like to contact us, fill out the form below or you can reach us here</h2>

        <div>Maine Dental Laboratory<br>832 E. Rand RD. Suite #21<br>Mt. Prospect, IL. 60056<br>Phone: (847)398-3977<br>Email: <a href="mailto:MaineDentalLab@comcast.net">mainedentallab@comcast.net</a></div>
        <br>

        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <form>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group user-name">
                                <label for="nameFive-first" class="sr-only">Name</label>
                                <input type="text" class="form-control" required="" id="nameFive-first" placeholder="First Name">
                            </div>

                            <div class="form-group user-email">
                                <label for="emailFive" class="sr-only">Email</label>
                                <input type="email" class="form-control" required="" id="emailFive" placeholder="Email Address">
                            </div>


                            <div class="form-group user-phone">
                                <label for="websiteOne" class="sr-only">Website</label>
                                <input type="text" class="form-control" required="" id="websiteOne" placeholder="Phone">
                            </div>
                        </div><!-- /.col-md-6 -->
                        <div class="col-md-6">
                            <div class="form-group user-message">
                                <label for="messageOne" class="sr-only">Message</label>
                                <textarea class="form-control" required="" id="messageOne" placeholder="Write Message"></textarea>
                            </div>
                        </div><!-- /.col-md-6 -->
                    </div><!-- /.row-->
                    <button type="submit" class="btn btn-primary">Send Message</button>
                </form>
            </div><!-- /.col-md-8 -->

        </div>

    </div>
</section>
<!-- .contact-form-->

<section class="map-section">
    <div id="googleMap" class="text-center">
        <iframe width="1000" height="500" frameborder="0" style="border:0"
                src="https://www.google.com/maps/embed/v1/place?key=AIzaSyCUXhrc8OBpm1_4pUOJdjU93a9ww3PuFio&q=832 E Rand Rd #21 Mt Prospect, IL 60056"
                allowfullscreen>
        </iframe>
    </div>
    <br><br>
</section>
    <!--.map-section-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Maine Dental Lab</title>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag 'application' %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <div id="main-wrapper">
      <!-- Page Preloader -->
      <div id="preloader">
        <div id="status">
          <div class="status-mes"></div>
        </div>
      </div>

      <div class="uc-mobile-menu-pusher">

        <div class="content-wrapper">

        <%= render partial: "partials/navbar" %>

        <%= yield %>

        <%= render partial: "partials/footer" %>

        </div>
        <!-- .content-wrapper -->
      </div>
      <!-- .offcanvas-pusher -->

      <div class="uc-mobile-menu uc-mobile-menu-effect">
        <button type="button" class="close" aria-hidden="true" data-toggle="offcanvas"
            id="uc-mobile-menu-close-btn">&times;</button>
        <div>
          <div>
              <ul id="menu">
                <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "Home", root_path %></li>
                <li class="<%= 'active' if current_page?(about_path) %>"><%= link_to "About", about_path %></li>
                <li class="<%= 'active' if current_page?(products_path) %>"><%= link_to "Products", products_path %></li>
                <li class="<%= 'active' if current_page?(contact_path) %>"><%= link_to "Contact", contact_path %></li>
              </ul>
          </div>
        </div>
      </div>
      <!-- .uc-mobile-menu -->
    </div>
    <!-- #main-wrapper -->
  </body>
</html>

app/views/partials/_footer.html.erb
<footer class="footer">

    <!-- Footer Widget Section -->
    <div class="footer-widget-section">
        <div class="container text-center">
            <div class="row">
                <div class="col-sm-4 footer-block">
                    <div class="footer-widget widget_text">
                        <div class="footer-logo">
                            <a href="#"><%= image_tag(image_path("logo.png"), :size => "310x160")%></a>
                        </div>
                        <p></p>

                    </div>
                </div><!-- /.col-sm-4 -->

                <div class="col-sm-4 footer-block">
                    <div class="footer-widget widget_text">
                        <h3></h3>
                        <p></p>
                    </div>
                </div><!-- /.col-sm-4 -->

                <div class="col-sm-4 footer-block last">
                    <div class="footer-widget widget_text">
                        <h3>Contact Us Today</h3>
                        <address>
                            Call Us (847)398-3977<br>
                            Send an Email to <a href="mailto:mainedentallab@comcast.net">mainedentallab@comcast.net</a><br>
                            Visit Us at 832 E. Rand Road. suite #21<br>
                            Mt. Prospect, IL 60056<br>
                        </address>

                        <ul class="list-inline social-links">
                        <!--
                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                            <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                        -->
                        </ul>
                    </div>
                </div><!-- /.col-sm-4 -->
            </div>
        </div>
    </div><!-- /.Footer Widget Section -->

    <div class="copyright-section">
        <div class="container clearfix">
                <span class="copytext">Copyright &copy; 2016</span>

            <ul class="list-inline pull-right">
                <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "Home", root_path %></li>
                <li class="<%= 'active' if current_page?(about_path) %>"><%= link_to "About", about_path %></li>
                <li class="<%= 'active' if current_page?(products_path) %>"><%= link_to "Products", products_path %></li>
                <li class="<%= 'active' if current_page?(contact_path) %>"><%= link_to "Contact", contact_path %></li>
            </ul>
        </div><!-- .container -->
    </div><!-- .copyright-section -->
</footer>
<!-- .footer -->

app/views/partials/_navbar.html.erb
<nav class="navbar m-menu navbar-default navbar-fixed-top">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/home"><%= image_tag(image_path("logo.png"), :size => "240x115", :class =>"top-logo")%></a>
        </div>



        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="#navbar-collapse-1">
            <!--
            <ul class="nav-cta hidden-xs">
                <li class="dropdown"><a href="#" data-toggle="dropdown" class="dropdown-toggle"><i
                        class="fa fa-search"></i></a>
                    <ul class="dropdown-menu">
                        <li>
                            <div class="head-search">
                                <form role="form">
                                    <!- - Input Group - ->
                                    <div class="input-group">
                                        <input type="text" class="form-control" placeholder="Type Something">
                                            <span class="input-group-btn">
                                              <button type="submit" class="btn btn-primary">Search</button>
                                            </span>
                                    </div>
                                </form>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
            -->

            <ul class="nav navbar-nav navbar-right main-nav">
                <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "Home", root_path %></li>
                <li class="<%= 'active' if current_page?(about_path) %>"><%= link_to "About", about_path %></li>
                <li class="<%= 'active' if current_page?(products_path) %>"><%= link_to "Products", products_path %></li>
                <li class="<%= 'active' if current_page?(contact_path) %>"><%= link_to "Contact", contact_path %></li>
                <!--
                <li class="dropdown m-menu-fw"><a href="#" data-toggle="dropdown" class="dropdown-toggle">Features
                    <span><i class="fa fa-angle-down"></i></span></a>
                    <ul class="dropdown-menu">
                        <li>
                            <div class="m-menu-content">
                                <ul class="col-sm-3">
                                    <li class="dropdown-header">Widget Haeder</li>
                                    <li><a href="#">Awesome Features</a></li>
                                    <li><a href="#">Clean Interface</a></li>
                                    <li><a href="#">Available Possibilities</a></li>
                                    <li><a href="#">Responsive Design</a></li>
                                    <li><a href="#">Pixel Perfect Graphics</a></li>
                                </ul>
                                <ul class="col-sm-3">
                                    <li class="dropdown-header">Widget Haeder</li>
                                    <li><a href="#">Awesome Features</a></li>
                                    <li><a href="#">Clean Interface</a></li>
                                    <li><a href="#">Available Possibilities</a></li>
                                    <li><a href="#">Responsive Design</a></li>
                                    <li><a href="#">Pixel Perfect Graphics</a></li>
                                </ul>
                                <ul class="col-sm-3">
                                    <li class="dropdown-header">Widget Haeder</li>
                                    <li><a href="#">Awesome Features</a></li>
                                    <li><a href="#">Clean Interface</a></li>
                                    <li><a href="#">Available Possibilities</a></li>
                                    <li><a href="#">Responsive Design</a></li>
                                    <li><a href="#">Pixel Perfect Graphics</a></li>
                                </ul>
                                <ul class="col-sm-3">
                                    <li class="dropdown-header">Widget Haeder</li>
                                    <li><a href="#">Awesome Features</a></li>
                                    <li><a href="#">Clean Interface</a></li>
                                    <li><a href="#">Available Possibilities</a></li>
                                    <li><a href="#">Responsive Design</a></li>
                                    <li><a href="#">Pixel Perfect Graphics</a></li>
                                </ul>
                            </div>
                        </li>
                    </ul>
                </li>
                -->
            </ul>

        </div>
        <!-- .navbar-collapse -->
    </div>
    <!-- .container -->
</nav>
<!-- .nav -->

app/views/products/cubex2.html.erb
<section class="single-page-title">
    <div class="container text-center">
        <h2>Cubex2</h2>
    </div>
</section>

<section class="x-features">
    <section class="section-title">
        <div class="container text-center">
            <h2>The Next Evolution in Zirconia</h2>
            <span class="bordered-icon"><i class="fa fa-circle-thin"></i></span>
        </div>
    </section>
    <div class="container">
        <div class="row">
            <div class="col-md-6 img-left">
                <%= image_tag(image_path("cubex-graphics.png"), size: "450x639")%>
            </div>
            <div class="col-md-6">
                <div class="promo-block-wrapper clearfix">
                    <div class="promo-content">
                        
                        <p>The new cubeX2 material combines the known positive properties of zirconia with a significant increase in translucency (49% translucency), making it ideal for anterior and posterior applications up to 3-unit bridgework in all tooth positions. Highly biocompatible, cubeX2 is the ideal restorative material for today’s dentistry, offering the translucency of a lithium disilicate while retaining the strength of zirconia (720 MPa’s). Unlike current glass ceramics, cubeX2 allows for a conservative feather edge preparation due to its high strength. Dentists no longer have to choose between traditional zirconia and lithium disilicate…cubeX2 has both strength and beauty!</p>
                    </div>
                </div>

                <div class="promo-block-wrapper clearfix">

                    <div class="promo-content">
                        <h3>Clinical Indications</h3>

                        <p>cubeX2 is indicated for single crowns and 3-unit bridgework in all tooth positions.</p>
                    </div>
                </div>

                <div class="promo-block-wrapper clearfix">

                    <div class="promo-content last-type">
                        <h3>Preparation Requirements</h3>

                        <p>cubeX2 requires less tooth preparation than is required for lithium disilicate. Ideally, a .8 mm chamfer or rounded shoulder prep is preferred, however a feather-edge margin is acceptable with 1.0 – 1.5 mm occlusal reduction.</p><br>

                        <%= image_tag(image_path("cubex-prep-guide.png"), size: "500x250")%>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


<section class="x-features">
    <section class="section-title">
        <div class="container text-center">
            <h2>Cementation</h2>
            <span class="bordered-icon"><i class="fa fa-circle-thin"></i></span>
        </div>
    </section>
    <div class="container">
        <div class="row">
            <div class="col-md-6 img-left">
                <%= image_tag(image_path("paste.png"), size: "400x360")%>
            </div>
            <div class="col-md-6">
                <div class="promo-block-wrapper clearfix">
                    <div class="promo-content">
                        
                        <p>Recent research has shown that saliva contamination can hinder the bonding of zirconia based products. When a zirconia crown or bridge is tried in the patient’s mouth and comes in contact with saliva, the phosphate groups in the saliva bind to the zirconia oxide and cannot be rinsed out with water. Attempting to use phosphoric acid (which is full of phosphate groups) to ‘clean out’ the saliva only makes the problem worse.
                        <br>
												To successfully remove saliva, it is now suggested that after try-in and before priming, the crown should be cleaned with Ivoclean, a zirconia oxide solution from Ivoclar Vivadent. This zirconia oxide solution is placed inside the restoration for 20 seconds and then rinsed out. Due to the large concentration of free zirconia oxide in the Ivoclean, it acts as a sponge and binds to the phosphate groups that were previously bonded to the restoration.</p>
                    </div>
                </div>

                <div class="promo-block-wrapper clearfix">

                    <div class="promo-content">
                        <h3>Suggested Cementation Protocol:</h3>

                        <p>1. Try-in zirconia-based restoration<br>
												2. Rinse saliva out of restoration with water<br>
												3. Place Ivoclean in restoration for 20 seconds,
												rinse and dry<br>
												4. Apply primer and then cement with product of
												your choice</p>
                    </div>
                </div>
                
                <div class="promo-block-wrapper clearfix">

                    <div class="promo-content">
                        <h3>Cementation Recommendations:</h3>

                        <p>• Ceramir® Crown & Bridge (Doxa Dental) or a resin-reinforced glass ionomer cement such as RelyX™ Luting Cement (3M ESPE) or GC Fuji Plus™ (GC America)<br> 
                        • For short or over-tapered preparations, use a resin cement such as RelyX Unicem (3M ESPE) or Panavia™ F2.0 (Kuraray)</p>
                    </div>
                </div>

                <div class="promo-block-wrapper clearfix">

                    <div class="promo-content">
                        <h3>Finishing and Polishing</h3>

                        <p>Maine Dental Lab recommends the Brasseler USA® Dialite® ZR Kit for finishing and polishing cubeX2 and BioZX2 zirconia products. This two-step system allows you to quickly achieve maximum surface smoothness, enhancing your restoration’s longevity and minimizing wear to opposing dentition.
                        <br>
												<b>Important: Be sure to use adequate water when adjusting.</b></p>
                    </div>
                </div>

            </div>
        </div>
    </div>
</section>